- hosts: '{{hosts}}'
  user: '{{user}}'
  sudo: yes
  tasks:
     - include: ./roles/common/tasks/setup.yml 
     - include: ./roles/memcached/tasks/memcached.yml
     - name: memcached起動&自動起動on
       service: name=memcached enabled="yes" state=started 
