- hosts: '{{hosts}}'
  user: '{{user}}'
  sudo: yes
  tasks:
     - include: ./roles/common/tasks/setup.yml
     - include: ./roles/mysql/tasks/mysql5.6.yml

     - name: master用cnfを配置
       template: src=./mysql/templates/my_master.cnf dest=/etc/my.cnf owner="root" group="root"
     
     - service: name=mysql enabled="yes" state=running
