# -*- mode: ruby -*-
# vi: set ft=ruby :

# All Vagrant configuration is done below. The "2" in Vagrant.configure
# configures the configuration version (we support older styles for
# backwards compatibility). Please don't change it unless you know what
# you're doing.
Vagrant.configure(2) do |config|

  config.vm.define :centos do |server|
    server.vm.box = "centos6.5"
    server.vm.network :private_network, ip:"192.168.10.10"
    server.ssh.insert_key=false
    #server.vm.provision :ansible do |ansible|
    #  ansible.playbook = "../Playbook/centos6.5.yml"
    #  ansible.inventory_path = "hosts"
    #end
  end
end
