# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define :web01 do |web|
     web.vm.box = "centos6.5"
     web.vm.network :private_network, ip:"192.168.20.10"
     web.ssh.insert_key=false
     web.vm.provision :ansible do |ansible|
      ansible.playbook = "../Playbook/web_server.yml"
      ansible.inventory_path = "hosts"
    end
  end
end
